#version: '3.9'
import keys

networks:
  tig-net:
    driver: bridge

volumes:
  tig-data:

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    environment:


#Info for Influx DB
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_DB: keys.INFLUXDB_DB
      INFLUXDB_ADMIN_USER: keys.INFLUXDB_ADMIN_USER
      INFLUXDB_ADMIN_PASSWORD: keys.INFLUXDB_ADMIN_PASSWORD
    networks:
      - tig-net
    volumes:
      - tig-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
    
      GF_SECURITY_ADMIN_USER: keys.GF_SECURITY_ADMIN_USER # Replace this before starting the containers
      GF_SECURITY_ADMIN_PASSWORD: keys.GF_SECURITY_ADMIN_PASSWORD # Replace this before starting the containers
    networks:
      - tig-net
    volumes:
      - tig-data:/var/lib/grafana
    restart: always

  telegraf:
    image: telegraf:latest
    depends_on:
      - "influxdb"
    environment:
      HOST_NAME: "telegraf"
      INFLUXDB_HOST: "influxdb"
      INFLUXDB_PORT: "8086"
      DATABASE: "" # THIS WILL BE REPLACED
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    tty: true
    networks:
      - tig-net
    privileged: true
